#ifndef LEBIRUN_RAW_SYSCALL_H
#define LEBIRUN_RAW_SYSCALL_H

#define LEBIRUN_SYSCALL_FLAG 0x80000000u

#define LEB_SYSCALL_EXIT 0u
#define LEB_SYSCALL_WRITE 1u
#define LEB_SYSCALL_GETPID 2u
#define LEB_SYSCALL_READ 3u
#define LEB_SYSCALL_YIELD 4u
#define LEB_SYSCALL_SLEEP 5u
#define LEB_SYSCALL_WAITPID 6u
#define LEB_SYSCALL_SBRK 7u
#define LEB_SYSCALL_MMAP 8u
#define LEB_SYSCALL_KILL 9u
#define LEB_SYSCALL_GETTICKS 10u
#define LEB_SYSCALL_TIME 11u
#define LEB_SYSCALL_ISATTY 12u
#define LEB_SYSCALL_FORK 13u
#define LEB_SYSCALL_EXEC 14u
#define LEB_SYSCALL_INITRD_COUNT 15u
#define LEB_SYSCALL_INITRD_STAT 16u
#define LEB_SYSCALL_INITRD_READ 17u
#define LEB_SYSCALL_OPEN 18u
#define LEB_SYSCALL_CLOSE 19u
#define LEB_SYSCALL_FSTAT 20u
#define LEB_SYSCALL_FB_PUTPIXEL 21u
#define LEB_SYSCALL_FB_SETCOLORS 22u
#define LEB_SYSCALL_FB_GETINFO 23u
#define LEB_SYSCALL_FB_CLEAR 24u
#define LEB_SYSCALL_CONSOLE_SWITCH 25u
#define LEB_SYSCALL_CONSOLE_GETCUR 26u
#define LEB_SYSCALL_CONSOLE_CLEAR 27u
#define LEB_SYSCALL_VFS_OPEN 28u
#define LEB_SYSCALL_VFS_CLOSE 29u
#define LEB_SYSCALL_VFS_READ 30u
#define LEB_SYSCALL_VFS_READDIR 31u
#define LEB_SYSCALL_VFS_STAT 32u
#define LEB_SYSCALL_VFS_MOUNTS 33u
#define LEB_SYSCALL_VFS_WRITE 34u
#define LEB_SYSCALL_VFS_CREATE 35u
#define LEB_SYSCALL_VFS_MKDIR 36u
#define LEB_SYSCALL_VFS_UNLINK 37u
#define LEB_SYSCALL_CONSOLE_SETCURSOR 38u
#define LEB_SYSCALL_READ_NB 39u
#define LEB_SYSCALL_SATA_TEST 40u
#define LEB_SYSCALL_SATA_INFO 41u
#define LEB_SYSCALL_SATA_SMART 42u
#define LEB_SYSCALL_SATA_IRQ 43u
#define LEB_SYSCALL_NET_IFCONFIG 44u
#define LEB_SYSCALL_NET_PING 45u
#define LEB_SYSCALL_NET_ARP 46u
#define LEB_SYSCALL_NET_DNS 47u
#define LEB_SYSCALL_NET_DHCP 48u
#define LEB_SYSCALL_NET_GETINFO 49u
#define LEB_SYSCALL_NET_ARP_GET 50u
#define LEB_SYSCALL_NET_PING_ONE 51u
#define LEB_SYSCALL_NET_DNS_RESOLVE 52u
#define LEB_SYSCALL_NET_HTTP_GET 53u
#define LEB_SYSCALL_TCGETATTR 54u
#define LEB_SYSCALL_TCSETATTR 55u
#define LEB_SYSCALL_IOCTL 56u
#define LEB_SYSCALL_TCFLUSH 57u
#define LEB_SYSCALL_TCFLOW 58u
#define LEB_SYSCALL_TCDRAIN 59u
#define LEB_SYSCALL_TCGETPGRP 60u
#define LEB_SYSCALL_TCSETPGRP 61u
#define LEB_SYSCALL_WRITEV 62u
#define LEB_SYSCALL_LSEEK 63u
#define LEB_SYSCALL_EXECVE 64u
#define LEB_SYSCALL_DUP 65u
#define LEB_SYSCALL_DUP2 66u
#define LEB_SYSCALL_PIPE 67u
#define LEB_SYSCALL_SIGACTION 68u
#define LEB_SYSCALL_SIGPROCMASK 69u
#define LEB_SYSCALL_STAT 71u
#define LEB_SYSCALL_GETCWD 72u
#define LEB_SYSCALL_CHDIR 73u
#define LEB_SYSCALL_ACCESS 74u
#define LEB_SYSCALL_CLOCK_GETTIME 75u
#define LEB_SYSCALL_GETTIMEOFDAY 76u
#define LEB_SYSCALL_MUNMAP 77u
#define LEB_SYSCALL_MPROTECT 78u
#define LEB_SYSCALL_FCNTL 79u
#define LEB_SYSCALL_GETDENTS 80u
#define LEB_SYSCALL_TRUNCATE 81u
#define LEB_SYSCALL_FTRUNCATE 82u
#define LEB_SYSCALL_RENAME 83u
#define LEB_SYSCALL_LINK 84u
#define LEB_SYSCALL_SYMLINK 85u
#define LEB_SYSCALL_READLINK 86u
#define LEB_SYSCALL_UMASK 87u
#define LEB_SYSCALL_SELECT 88u
#define LEB_SYSCALL_POLL 89u
#define LEB_SYSCALL_PPOLL 90u
#define LEB_SYSCALL_SOCKET 91u
#define LEB_SYSCALL_SOCKETPAIR 92u
#define LEB_SYSCALL_BIND 93u
#define LEB_SYSCALL_CONNECT 94u
#define LEB_SYSCALL_LISTEN 95u
#define LEB_SYSCALL_ACCEPT 96u
#define LEB_SYSCALL_ACCEPT4 97u
#define LEB_SYSCALL_GETSOCKOPT 98u
#define LEB_SYSCALL_SETSOCKOPT 99u
#define LEB_SYSCALL_GETSOCKNAME 100u
#define LEB_SYSCALL_GETPEERNAME 101u
#define LEB_SYSCALL_SENDTO 102u
#define LEB_SYSCALL_SENDMSG 103u
#define LEB_SYSCALL_RECVFROM 104u
#define LEB_SYSCALL_RECVMSG 105u
#define LEB_SYSCALL_SHUTDOWN 106u
#define LEB_SYSCALL_OPENAT 107u
#define LEB_SYSCALL_MKDIRAT 108u
#define LEB_SYSCALL_MKNODAT 109u
#define LEB_SYSCALL_FCHOWNAT 110u
#define LEB_SYSCALL_UNLINKAT 111u
#define LEB_SYSCALL_RENAMEAT 112u
#define LEB_SYSCALL_LINKAT 113u
#define LEB_SYSCALL_SYMLINKAT 114u
#define LEB_SYSCALL_READLINKAT 115u
#define LEB_SYSCALL_FCHMODAT 116u
#define LEB_SYSCALL_FACCESSAT 117u
#define LEB_SYSCALL_FSTATAT 118u
#define LEB_SYSCALL_UTIMENSAT 119u
#define LEB_SYSCALL_RENAMEAT2 120u
#define LEB_SYSCALL_RT_SIGACTION 121u
#define LEB_SYSCALL_RT_SIGPROCMASK 122u
#define LEB_SYSCALL_RT_SIGPENDING 123u
#define LEB_SYSCALL_RT_SIGSUSPEND 124u
#define LEB_SYSCALL_RT_SIGRETURN 125u
#define LEB_SYSCALL_RT_SIGTIMEDWAIT 126u
#define LEB_SYSCALL_RT_SIGQUEUEINFO 127u
#define LEB_SYSCALL_TGKILL 128u
#define LEB_SYSCALL_TKILL 129u
#define LEB_SYSCALL_SIGALTSTACK 130u
#define LEB_SYSCALL_PAUSE 131u
#define LEB_SYSCALL_ALARM 132u
#define LEB_SYSCALL_GETUID 133u
#define LEB_SYSCALL_GETGID 134u
#define LEB_SYSCALL_GETEUID 135u
#define LEB_SYSCALL_GETEGID 136u
#define LEB_SYSCALL_SETUID 137u
#define LEB_SYSCALL_SETGID 138u
#define LEB_SYSCALL_SETEUID 139u
#define LEB_SYSCALL_SETEGID 140u
#define LEB_SYSCALL_SETREUID 141u
#define LEB_SYSCALL_SETREGID 142u
#define LEB_SYSCALL_SETRESUID 143u
#define LEB_SYSCALL_SETRESGID 144u
#define LEB_SYSCALL_GETRESUID 145u
#define LEB_SYSCALL_GETRESGID 146u
#define LEB_SYSCALL_SETFSUID 147u
#define LEB_SYSCALL_SETFSGID 148u
#define LEB_SYSCALL_GETGROUPS 149u
#define LEB_SYSCALL_SETGROUPS 150u
#define LEB_SYSCALL_GETPGID 151u
#define LEB_SYSCALL_SETPGID 152u
#define LEB_SYSCALL_GETPGRP 153u
#define LEB_SYSCALL_SETSID 154u
#define LEB_SYSCALL_GETSID 155u
#define LEB_SYSCALL_GETPPID 156u
#define LEB_SYSCALL_GETPID2 157u
#define LEB_SYSCALL_GETTID 158u
#define LEB_SYSCALL_UNAME 159u
#define LEB_SYSCALL_SYSINFO 160u
#define LEB_SYSCALL_GETRLIMIT 161u
#define LEB_SYSCALL_SETRLIMIT 162u
#define LEB_SYSCALL_GETRUSAGE 163u
#define LEB_SYSCALL_PRLIMIT64 164u
#define LEB_SYSCALL_MMAP2 165u
#define LEB_SYSCALL_MREMAP 166u
#define LEB_SYSCALL_MADVISE 167u
#define LEB_SYSCALL_MINCORE 168u
#define LEB_SYSCALL_PREAD64 169u
#define LEB_SYSCALL_PWRITE64 170u
#define LEB_SYSCALL_READV 171u
#define LEB_SYSCALL_FCHDIR 172u
#define LEB_SYSCALL_FCHMOD 173u
#define LEB_SYSCALL_FCHOWN 174u
#define LEB_SYSCALL_FSYNC 175u
#define LEB_SYSCALL_FDATASYNC 176u
#define LEB_SYSCALL_FLOCK 177u
#define LEB_SYSCALL_GETDENTS64 178u
#define LEB_SYSCALL_DUP3 179u
#define LEB_SYSCALL_PIPE2 180u
#define LEB_SYSCALL_EVENTFD 181u
#define LEB_SYSCALL_EVENTFD2 182u
#define LEB_SYSCALL_EPOLL_CREATE 183u
#define LEB_SYSCALL_EPOLL_CREATE1 184u
#define LEB_SYSCALL_EPOLL_CTL 185u
#define LEB_SYSCALL_EPOLL_WAIT 186u
#define LEB_SYSCALL_EPOLL_PWAIT 187u
#define LEB_SYSCALL_SET_TID_ADDRESS 188u
#define LEB_SYSCALL_FUTEX 189u
#define LEB_SYSCALL_SET_ROBUST_LIST 190u
#define LEB_SYSCALL_GET_ROBUST_LIST 191u
#define LEB_SYSCALL_CLONE 192u
#define LEB_SYSCALL_VFORK 193u
#define LEB_SYSCALL_WAIT4 194u
#define LEB_SYSCALL_WAITID 195u
#define LEB_SYSCALL_GETRANDOM 196u
#define LEB_SYSCALL_PRCTL 197u
#define LEB_SYSCALL_ARCH_PRCTL 198u
#define LEB_SYSCALL_TIMERFD_CREATE 199u
#define LEB_SYSCALL_TIMERFD_SETTIME 200u
#define LEB_SYSCALL_TIMERFD_GETTIME 201u
#define LEB_SYSCALL_SIGNALFD 202u
#define LEB_SYSCALL_SIGNALFD4 203u
#define LEB_SYSCALL_INOTIFY_INIT 204u
#define LEB_SYSCALL_INOTIFY_INIT1 205u
#define LEB_SYSCALL_INOTIFY_ADD_WATCH 206u
#define LEB_SYSCALL_INOTIFY_RM_WATCH 207u
#define LEB_SYSCALL_POSIX_OPENPT 208u
#define LEB_SYSCALL_GRANTPT 209u
#define LEB_SYSCALL_UNLOCKPT 210u
#define LEB_SYSCALL_PTSNAME 211u
#define LEB_SYSCALL_SETITIMER 212u
#define LEB_SYSCALL_GETITIMER 213u
#define LEB_SYSCALL_CHMOD 214u
#define LEB_SYSCALL_CHOWN 215u
#define LEB_SYSCALL_LCHOWN 216u
#define LEB_SYSCALL_NANOSLEEP 217u
#define LEB_SYSCALL_SIGRETURN 218u
#define LEB_SYSCALL_SETENV 219u
#define LEB_SYSCALL_GETENV 220u
#define LEB_SYSCALL_UNSETENV 221u
#define LEB_SYSCALL_CLEARENV 222u
#define LEB_SYSCALL_PTHREAD_CREATE 223u
#define LEB_SYSCALL_PTHREAD_EXIT 224u
#define LEB_SYSCALL_PTHREAD_JOIN 225u
#define LEB_SYSCALL_PTHREAD_DETACH 226u
#define LEB_SYSCALL_PTHREAD_SELF 227u
#define LEB_SYSCALL_PTHREAD_MUTEX_INIT 228u
#define LEB_SYSCALL_PTHREAD_MUTEX_DESTROY 229u
#define LEB_SYSCALL_PTHREAD_MUTEX_LOCK 230u
#define LEB_SYSCALL_PTHREAD_MUTEX_TRYLOCK 231u
#define LEB_SYSCALL_PTHREAD_MUTEX_UNLOCK 232u
#define LEB_SYSCALL_PTHREAD_COND_INIT 233u
#define LEB_SYSCALL_PTHREAD_COND_DESTROY 234u
#define LEB_SYSCALL_PTHREAD_COND_WAIT 235u
#define LEB_SYSCALL_PTHREAD_COND_SIGNAL 236u
#define LEB_SYSCALL_PTHREAD_COND_BROADCAST 237u
#define LEB_SYSCALL_SHMGET 238u
#define LEB_SYSCALL_SHMAT 239u
#define LEB_SYSCALL_SHMDT 240u
#define LEB_SYSCALL_SHMCTL 241u
#define LEB_SYSCALL_SHM_OPEN 242u
#define LEB_SYSCALL_SHM_UNLINK 243u
#define LEB_SYSCALL_DLOPEN 244u
#define LEB_SYSCALL_DLSYM 245u
#define LEB_SYSCALL_DLCLOSE 246u
#define LEB_SYSCALL_DLERROR 247u
#define LEB_SYSCALL_REGCOMP 248u
#define LEB_SYSCALL_REGEXEC 249u
#define LEB_SYSCALL_REGFREE 250u
#define LEB_SYSCALL_REGERROR 251u
#define LEB_SYSCALL_FNMATCH 252u
#define LEB_SYSCALL_GLOB 253u
#define LEB_SYSCALL_GLOBFREE 254u
#define LEB_SYSCALL_SSCANF 255u
#define LEB_SYSCALL_SCANF_GETCHAR 256u
#define LEB_SYSCALL_REGSUB 257u
#define LEB_SYSCALL_REGEXEC_EX 258u
#define LEB_SYSCALL_FB_SET_MODE 259u
#define LEB_SYSCALL_FB_GET_DETAILED_INFO 260u
#define LEB_SYSCALL_FB_GET_CAPS 261u
#define LEB_SYSCALL_STATFS 262u
#define LEB_SYSCALL_FSTATFS 263u
#define LEB_SYSCALL_NET_HTTP_POST 264u
#define LEB_SYSCALL_PSELECT6 265u
#define LEB_SYSCALL_GETPRIORITY 266u
#define LEB_SYSCALL_SETPRIORITY 267u
#define LEB_SYSCALL_PIVOT_ROOT 268u
#define LEB_SYSCALL_REBOOT 269u
#define LEB_SYSCALL_CONSOLE_SETID 270u
#define LEB_SYSCALL_CRYPTO 271u
#define LEB_SYSCALL_VFS_MOUNT 272u
#define LEB_SYSCALL_VFS_UMOUNT 273u
#define LEB_SYSCALL_PANIC 274u
#define LEB_SYSCALL_BLOCKDEV_RESCAN 275u
#define LEB_SYSCALL_NET_HTTP_GET_ALLOC 276u
#define LEB_SYSCALL_LKE_LOAD 277u
#define LEB_SYSCALL_LKE_UNLOAD 278u
#define LEB_SYSCALL_LKE_LIST 279u
#define LEB_SYSCALL_IPV67 280u
#define LEB_SYSCALL_SCHED_SETPARAM 281u
#define LEB_SYSCALL_SCHED_GETPARAM 282u
#define LEB_SYSCALL_SCHED_SETSCHEDULER 283u
#define LEB_SYSCALL_SCHED_GETSCHEDULER 284u
#define LEB_SYSCALL_SCHED_GET_PRIORITY_MAX 285u
#define LEB_SYSCALL_SCHED_GET_PRIORITY_MIN 286u
#define LEB_SYSCALL_SCHED_RR_GET_INTERVAL 287u
#define LEB_NR_SYSCALLS 288u

#define LEB_MS_RDONLY   1
#define LEB_MS_REMOUNT  32

static __inline__ long leb_syscall0(unsigned int n) {
	long ret;
	__asm__ __volatile__("int $0x80" : "=a"(ret) : "a"(n | LEBIRUN_SYSCALL_FLAG) : "memory");
	return ret;
}

static __inline__ long leb_syscall1(unsigned int n, long a1) {
	long ret;
	__asm__ __volatile__("int $0x80" : "=a"(ret) : "a"(n | LEBIRUN_SYSCALL_FLAG), "b"(a1) : "memory");
	return ret;
}

static __inline__ long leb_syscall2(unsigned int n, long a1, long a2) {
	long ret;
	__asm__ __volatile__("int $0x80" : "=a"(ret) : "a"(n | LEBIRUN_SYSCALL_FLAG), "b"(a1), "c"(a2) : "memory");
	return ret;
}

static __inline__ long leb_syscall3(unsigned int n, long a1, long a2, long a3) {
	long ret;
	__asm__ __volatile__("int $0x80" : "=a"(ret) : "a"(n | LEBIRUN_SYSCALL_FLAG), "b"(a1), "c"(a2), "d"(a3) : "memory");
	return ret;
}

static __inline__ long leb_syscall4(unsigned int n, long a1, long a2, long a3, long a4) {
	long ret;
	__asm__ __volatile__("int $0x80" : "=a"(ret) : "a"(n | LEBIRUN_SYSCALL_FLAG), "b"(a1), "c"(a2), "d"(a3), "S"(a4) : "memory");
	return ret;
}

#endif
