CONFIG_FILE := $(if $(wildcard ../.config),../.config,../.config.default)

define read_bool
$(if $(filter y yes 1 true enable enabled,$(shell if [ -f "$(CONFIG_FILE)" ] && grep -q '^$(1)=' "$(CONFIG_FILE)" 2>/dev/null; then grep '^$(1)=' "$(CONFIG_FILE)" 2>/dev/null | tail -n 1 | cut -d= -f2; elif [ -f "../.config.default" ]; then grep '^$(1)=' "../.config.default" 2>/dev/null | tail -n 1 | cut -d= -f2; fi)),1,0)
endef

CONFIG_DEBUG_MEMORY := $(call read_bool,DEBUG_MEMORY)
CONFIG_DEBUG_TASK := $(call read_bool,DEBUG_TASK)
CONFIG_DEBUG_VFS := $(call read_bool,DEBUG_VFS)
CONFIG_DEBUG_RAMFS := $(call read_bool,DEBUG_RAMFS)
CONFIG_DEBUG_INITRD := $(CONFIG_DEBUG_RAMFS)
CONFIG_DEBUG_ELF := $(call read_bool,DEBUG_ELF)
CONFIG_DEBUG_SYSCALL := $(call read_bool,DEBUG_SYSCALL)
CONFIG_DEBUG_IDT := $(call read_bool,DEBUG_IDT)
CONFIG_DEBUG_DRIVER := $(call read_bool,DEBUG_DRIVER)
CONFIG_DEBUG_FS_EXT4 := $(call read_bool,DEBUG_FS_EXT4)
CONFIG_DEBUG_FS_OTHER := $(call read_bool,DEBUG_FS_OTHER)
CONFIG_DEBUG_SIGNAL := $(call read_bool,DEBUG_SIGNAL)
CONFIG_DEBUG_IPC := $(call read_bool,DEBUG_IPC)
CONFIG_DEBUG_BOOT_VERBOSE := $(call read_bool,DEBUG_BOOT_VERBOSE)
CONFIG_DEBUG_BOOT_VFS := $(CONFIG_DEBUG_BOOT_VERBOSE)
CONFIG_DEBUG_BOOT_MODULES := $(CONFIG_DEBUG_BOOT_VERBOSE)
CONFIG_DEBUG_BOOT_HW := $(CONFIG_DEBUG_BOOT_VERBOSE)
CONFIG_VIRT_VFL := $(call read_bool,VIRT_VFL)
CONFIG_DRIVER_AHCI := $(call read_bool,DRIVER_AHCI)
CONFIG_DRIVER_PS2_KEYBOARD := $(call read_bool,DRIVER_PS2_KEYBOARD)
CONFIG_DRIVER_PS2_MOUSE := $(call read_bool,DRIVER_PS2_MOUSE)
CONFIG_DRIVER_NET := $(call read_bool,DRIVER_NET)
CONFIG_DRIVER_NET_E1000 := $(call read_bool,DRIVER_NET_E1000)
CONFIG_DRIVER_NET_IPV67 := $(call read_bool,DRIVER_NET_IPV67)

CPPFLAGS:=$(CPPFLAGS) \
	-DCONFIG_DEBUG_MEMORY=$(CONFIG_DEBUG_MEMORY) \
	-DCONFIG_DEBUG_TASK=$(CONFIG_DEBUG_TASK) \
	-DCONFIG_DEBUG_VFS=$(CONFIG_DEBUG_VFS) \
	-DCONFIG_DEBUG_RAMFS=$(CONFIG_DEBUG_RAMFS) \
	-DCONFIG_DEBUG_INITRD=$(CONFIG_DEBUG_INITRD) \
	-DCONFIG_DEBUG_ELF=$(CONFIG_DEBUG_ELF) \
	-DCONFIG_DEBUG_SYSCALL=$(CONFIG_DEBUG_SYSCALL) \
	-DCONFIG_DEBUG_IDT=$(CONFIG_DEBUG_IDT) \
	-DCONFIG_DEBUG_DRIVER=$(CONFIG_DEBUG_DRIVER) \
	-DCONFIG_DEBUG_FS_EXT4=$(CONFIG_DEBUG_FS_EXT4) \
	-DCONFIG_DEBUG_FS_OTHER=$(CONFIG_DEBUG_FS_OTHER) \
	-DCONFIG_DEBUG_SIGNAL=$(CONFIG_DEBUG_SIGNAL) \
	-DCONFIG_DEBUG_IPC=$(CONFIG_DEBUG_IPC) \
	-DCONFIG_DEBUG_BOOT_VERBOSE=$(CONFIG_DEBUG_BOOT_VERBOSE) \
	-DCONFIG_DEBUG_BOOT_VFS=$(CONFIG_DEBUG_BOOT_VFS) \
	-DCONFIG_DEBUG_BOOT_MODULES=$(CONFIG_DEBUG_BOOT_MODULES) \
	-DCONFIG_DEBUG_BOOT_HW=$(CONFIG_DEBUG_BOOT_HW) \
	-DCONFIG_VIRT_VFL=$(CONFIG_VIRT_VFL) \
	-DCONFIG_DRIVER_AHCI=$(CONFIG_DRIVER_AHCI) \
	-DCONFIG_DRIVER_PS2_KEYBOARD=$(CONFIG_DRIVER_PS2_KEYBOARD) \
	-DCONFIG_DRIVER_PS2_MOUSE=$(CONFIG_DRIVER_PS2_MOUSE) \
	-DCONFIG_DRIVER_NET=$(CONFIG_DRIVER_NET) \
	-DCONFIG_DRIVER_NET_E1000=$(CONFIG_DRIVER_NET_E1000) \
	-DCONFIG_DRIVER_NET_IPV67=$(CONFIG_DRIVER_NET_IPV67)
