CONFIG_FILE := $(if $(wildcard ../.config),../.config,../.config.default)

define read_bool
$(if $(filter y yes 1 true enable enabled,$(shell [ -f "$(CONFIG_FILE)" ] && grep '^$(1)=' "$(CONFIG_FILE)" 2>/dev/null | cut -d= -f2)),1,0)
endef

CONFIG_DEBUG_MEMORY := $(call read_bool,DEBUG_MEMORY)
CONFIG_DEBUG_TASK := $(call read_bool,DEBUG_TASK)
CONFIG_DEBUG_VFS := $(call read_bool,DEBUG_VFS)
CONFIG_DEBUG_RAMFS := $(call read_bool,DEBUG_RAMFS)
CONFIG_DEBUG_INITRD := $(CONFIG_DEBUG_RAMFS)
CONFIG_DEBUG_ELF := $(call read_bool,DEBUG_ELF)
CONFIG_DEBUG_SYSCALL := $(call read_bool,DEBUG_SYSCALL)
CONFIG_DEBUG_IDT := $(call read_bool,DEBUG_IDT)
CONFIG_DEBUG_DRIVER := $(call read_bool,DEBUG_DRIVER)
CONFIG_DEBUG_FS_EXT4 := $(call read_bool,DEBUG_FS_EXT4)
CONFIG_DEBUG_FS_OTHER := $(call read_bool,DEBUG_FS_OTHER)
CONFIG_DEBUG_SIGNAL := $(call read_bool,DEBUG_SIGNAL)
CONFIG_DEBUG_IPC := $(call read_bool,DEBUG_IPC)
CONFIG_DEBUG_BOOT_VERBOSE := $(call read_bool,DEBUG_BOOT_VERBOSE)
CONFIG_DEBUG_BOOT_VFS := $(CONFIG_DEBUG_BOOT_VERBOSE)
CONFIG_DEBUG_BOOT_MODULES := $(CONFIG_DEBUG_BOOT_VERBOSE)
CONFIG_DEBUG_BOOT_HW := $(CONFIG_DEBUG_BOOT_VERBOSE)
CONFIG_VIRT_VFL := $(call read_bool,VIRT_VFL)

CPPFLAGS:=$(CPPFLAGS) \
	-DCONFIG_DEBUG_MEMORY=$(CONFIG_DEBUG_MEMORY) \
	-DCONFIG_DEBUG_TASK=$(CONFIG_DEBUG_TASK) \
	-DCONFIG_DEBUG_VFS=$(CONFIG_DEBUG_VFS) \
	-DCONFIG_DEBUG_RAMFS=$(CONFIG_DEBUG_RAMFS) \
	-DCONFIG_DEBUG_INITRD=$(CONFIG_DEBUG_INITRD) \
	-DCONFIG_DEBUG_ELF=$(CONFIG_DEBUG_ELF) \
	-DCONFIG_DEBUG_SYSCALL=$(CONFIG_DEBUG_SYSCALL) \
	-DCONFIG_DEBUG_IDT=$(CONFIG_DEBUG_IDT) \
	-DCONFIG_DEBUG_DRIVER=$(CONFIG_DEBUG_DRIVER) \
	-DCONFIG_DEBUG_FS_EXT4=$(CONFIG_DEBUG_FS_EXT4) \
	-DCONFIG_DEBUG_FS_OTHER=$(CONFIG_DEBUG_FS_OTHER) \
	-DCONFIG_DEBUG_SIGNAL=$(CONFIG_DEBUG_SIGNAL) \
	-DCONFIG_DEBUG_IPC=$(CONFIG_DEBUG_IPC) \
	-DCONFIG_DEBUG_BOOT_VERBOSE=$(CONFIG_DEBUG_BOOT_VERBOSE) \
	-DCONFIG_DEBUG_BOOT_VFS=$(CONFIG_DEBUG_BOOT_VFS) \
	-DCONFIG_DEBUG_BOOT_MODULES=$(CONFIG_DEBUG_BOOT_MODULES) \
	-DCONFIG_DEBUG_BOOT_HW=$(CONFIG_DEBUG_BOOT_HW) \
	-DCONFIG_VIRT_VFL=$(CONFIG_VIRT_VFL)
